
server:
  port: 9100

dubbo:
  application:
    name: manager
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181


spring:
  mvc:
    static-path-pattern=/**:
  application:
    name: beibei-server-web-portal
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html