
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/beibei_goods?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver


beibei:
  elasticsearch:
    host: 192.168.0.221
    port: 9200
    index: goods
    type: sku


dubbo:
  application:
    id: search
    name: search
  protocol:
    id: dubbo
    name: dubbo
    port: "20882"
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181

